<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8m3itok\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8m3itok/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8m3itok.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8m3itok\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8m3itok\appDevDebugProjectContainer([
    'container.build_hash' => '8m3itok',
    'container.build_id' => 'daf04305',
    'container.build_time' => 1615976865,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8m3itok');
