<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9jliaa9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9jliaa9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9jliaa9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9jliaa9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9jliaa9\appDevDebugProjectContainer([
    'container.build_hash' => '9jliaa9',
    'container.build_id' => 'a8449750',
    'container.build_time' => 1618482551,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9jliaa9');
